- id: no-local-imports
  name: no-local-imports
  description: Ensure no local path sources exist in [tool.uv.sources]
  entry: no-local-imports
  language: python
  files: pyproject\.toml$
  pass_filenames: false
